// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBBkpgRw_ho4kvR1lEfJVFytS0RGSq35do",
    authDomain: "mealfresh-3b68f.firebaseapp.com",
    projectId: "mealfresh-3b68f",
    storageBucket: "mealfresh-3b68f.appspot.com",
    messagingSenderId: "167612952725",
    appId: "1:167612952725:web:642d5db6420ae8c8a92b9c",
    measurementId: "G-XPTRNH2PRJ",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBBkpgRw_ho4kvR1lEfJVFytS0RGSq35do",
    appId: "1:167612952725:web:642d5db6420ae8c8a92b9c",
    messagingSenderId: "167612952725",
    projectId: "mealfresh-3b68f",
    storageBucket: "mealfresh-3b68f.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBBkpgRw_ho4kvR1lEfJVFytS0RGSq35do",
    appId: "1:167612952725:web:642d5db6420ae8c8a92b9c",
    messagingSenderId: "167612952725",
    projectId: "mealfresh-3b68f",
    storageBucket: "mealfresh-3b68f.appspot.com",
    iosBundleId: 'com.example.frontEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyBBkpgRw_ho4kvR1lEfJVFytS0RGSq35do",
    appId: "1:167612952725:web:642d5db6420ae8c8a92b9c",
    messagingSenderId: "167612952725",
    projectId: "mealfresh-3b68f",
    storageBucket: "mealfresh-3b68f.appspot.com",
    iosBundleId: 'com.example.frontEnd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyBBkpgRw_ho4kvR1lEfJVFytS0RGSq35do",
    authDomain: "mealfresh-3b68f.firebaseapp.com",
    projectId: "mealfresh-3b68f",
    storageBucket: "mealfresh-3b68f.appspot.com",
    messagingSenderId: "167612952725",
    appId: "1:167612952725:web:642d5db6420ae8c8a92b9c",
    measurementId: "G-XPTRNH2PRJ",
  );
}
