// This file configures the Dart analyzer to enforce code quality rules and linting standards
// for the project. It includes predefined lints and allows customizing specific rules.

// Include the Flutter lints configuration file which provides a set of recommended rules
// for Flutter projects to ensure good coding practices and consistent code style.
include: package:flutter_lints/flutter.yaml

linter:
  // Customize linting rules by enabling or disabling specific rules
  // The rules section allows fine-grained control over which lints are applied
  rules:
    // Example: Disable the 'avoid_print' rule which warns against using print statements
    // avoid_print: false
    
    // Example: Enable the 'prefer_single_quotes' rule which enforces single quote usage
    // prefer_single_quotes: true

    // Add more rules as needed to suit your project's coding standards

# Additional documentation and configuration options can be found at:
# https://dart.dev/guides/language/analysis-options